# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nickollas Coelho
email: nickollas.coelho@gmail.com
description: > Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nickollascoelho.com.br" # the base hostname & protocol for your site
twitter_username: nickollascoelho
github_username:  nickollascoelho

# Build settings
markdown: kramdown

exclude: ['package.json', 'src', 'node_modules']
